version: "3.7"
services:
    redis:
        image: "redis:alpine"          

    frontend:
        container_name: musiccollabWeb
        build:
            context: ./web
            dockerfile: Dockerfile
        image: musiccolab/web
        ports:
            - "3000:3000"
        volumes:
            - ./web:/usr/src/app
            - /usr/src/app/node_modules

    backend:
        container_name: musiccollabServer
        build:
            context: ./server
            dockerfile: Dockerfile
        image: musiccolab/server
        depends_on:
            - redis
        ports:
            - "4000:4000"
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
